[package]
name = "fe-resolver"
version = "0.26.0"
authors = ["The Fe Developers <snakecharmers@ethereum.org>"]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/ethereum/fe"
description = "Resolver lib for Fe."

[dependencies]
common.workspace = true

camino.workspace = true
glob.workspace = true
serde-semver.workspace = true
toml = "0.8"
serde = { version = "1", features = ["derive"] }
smol_str.workspace = true
tracing.workspace = true
url.workspace = true
