use std::evm::StorageMap

pub contract Counter {
    map: StorageMap<u256, u64, 0>
    count: u64,

    init(start: u64) uses (mut count) {
        count = start
    }

    recv CounterMsg {
        Increment uses (mut count, mut map) {
            map.set(0, count)
            count += 1
        }
        Get -> (u64, u64) uses (count, map) {
            (count, map.get(0))
        }
    }
}

msg CounterMsg {
    #[selector = 0x01]
    Increment,
    #[selector = 0x02]
    Get -> (u64, u64),
}
