use core::intrinsic::{__as_bytes, __keccak256}
use core::keccak
use std::evm::Address
use std::evm::effects::assert

trait SolCompat {
    const N: usize
    const SOL_TYPE: String<Self::N>
}

impl SolCompat for u256 {
    const N: usize = 7
    const SOL_TYPE: String<7> = "uint256"
}

impl SolCompat for Address {
    const N: usize = 7
    const SOL_TYPE: String<7> = "address"
}

impl SolCompat for Transfer {
    const N: usize = 8
    const SOL_TYPE: String<8> = "Transfer"
}

trait Event {
    const SIG: u256
}

struct Transfer { from: Address, to: Address, val: u256 }


impl Event for Transfer {
    const SIG: u256 = keccak((Transfer::SOL_TYPE, "(", Address::SOL_TYPE, ",", Address::SOL_TYPE, ",", u256::SOL_TYPE, ")"))
}

#[test]
fn transfer_sig() {
    assert(
        Transfer::SIG == 0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef,
    )
}
