use std::evm::{Create, Evm, RawMem}

#[contract_init(Parent)]
fn init() uses (mut evm: Evm) {
    let len = evm.code_region_len(runtime)
    let offset = evm.code_region_offset(runtime)
    evm.codecopy(dest: 0, offset, len)
    evm.return_data(0, len)
}

#[contract_runtime(Parent)]
fn runtime() uses (mut evm: Evm) {
    let len = evm.code_region_len(child::child_init)
    let offset = evm.code_region_offset(child::child_init)
    let dest = with (RawMem = evm) { allocate(bytes: len) }
    evm.codecopy(dest, offset, len)
    let addr = evm.create2(value: 0, offset: dest, len: len, salt: 0x1234)
    evm.mstore(0, addr.inner)
    evm.return_data(0, 32)
}

fn allocate(bytes: u256) -> u256 uses (mut mem: RawMem) {
    let mut ptr = mem.mload(0x40)
    if ptr == 0 {
        ptr = 0x60
    }
    mem.mstore(0x40, ptr + bytes)
    ptr
}
