[package]
name = "fe-test-files"
version = "0.10.0-alpha"
authors = ["The Fe Developers <snakecharmers@ethereum.org>"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/ethereum/fe"

[dependencies]
include_dir = "0.6.0"
walkdir = "2"
fe-common = {path = "../common", version = "^0.10.0-alpha"}
